apiVersion: v1
kind: Pod
metadata: 
  name: annotations
  labels:
    environment: dev
    project: expense
  annotations:
    cloud: aws
    tool: k8
spec:
  containers:
  - name: nginx
    image: nginx